version: '3.5'
services:
# Traefik - Reverse proxy FTW
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=ERROR"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # Homepage's
      - homepage.group=Reverse Proxy
      - homepage.name=Træfik
      - homepage.icon=${ICON_WEB}/traefik.png
      - homepage.href=http:${DOMAIN}:8080
      - homepage.widget.type=traefik
      - homepage.widget.url=http:${DOMAIN}:8080
    networks:
      traefik:
        ipv4_address: 172.18.0.10

# What's up Docker? - Just like watchtower but cooler
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 3000:3000
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.routers.whatsupdocker.rule=Host(`whatsupdocker.${DOMAIN}`)" # && PathPrefix(`/wud`)"
      - "traefik.http.routers.whatsupdocker.entrypoints=web"
      - "traefik.http.services.whatsupdocker.loadbalancer.server.port=3000"
      # Homepage's
      - homepage.group=Updates
      - homepage.name=What's up Docker
      - homepage.icon=${ICON_WEB}/wud-light.png
      - homepage.href=http://whatsupdocker.${DOMAIN}
      - homepage.widget.type=whatsupdocker
      - homepage.widget.url=http://whatsupdocker.${DOMAIN}
    networks:
      - traefik

# HomePage - Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - ${IMAGE_PATH}:/app/public/images
      - ${CONTAINER_PATH}/homepage/config:/app/config 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN}`)" # && PathPrefix(`/homepage`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - traefik

# Uptime-kuma - Playing ping pong with all the cool containers
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ${CONTAINER_PATH}/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 3001:3001
    restart: unless-stopped
    networks:
      - traefik
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.${DOMAIN}`)" # && PathPrefix(`/uptime-kuma`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=web"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      # Homepage's
      - homepage.group=Monitoring
      - homepage.name=Uptime-kuma
      - homepage.icon=${ICON_WEB}/uptime-kuma.png
      - homepage.href=http://uptime-kuma.${DOMAIN}
      - homepage.widget.type=uptimekuma
      - homepage.widget.url=http://uptime-kuma.${DOMAIN}
      - homepage.widget.slug=polvo

# Gotify - Outro app para receber notificações push
  gotify:
    image: gotify/server
    container_name: gotify
    # ports:
    #   - "80:80"
    volumes:
      - ${CONTAINER_PATH}/gotify/data:/app/data
    networks:
      - traefik
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.rule=Host(`gotify.${DOMAIN}`)" # && PathPrefix(`/gotify`)"
      - "traefik.http.routers.gotify.entrypoints=web"
      - "traefik.http.services.gotify.loadbalancer.server.port=80"
    restart: unless-stopped
      
networks:
  traefik:
    ipam:
      config:
        - subnet: 172.18.0.0/16