version: '3.5'
services:
# Traefik - Reverse proxy FTW
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=ERROR"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      traefik:
        ipv4_address: 172.18.0.10

# What's up Docker? - Just like watchtower but cooler
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 3000:3000
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.whatsupdocker.rule=Host(`whatsupdocker.hackerboy.xyz`)" # && PathPrefix(`/wud`)"
      - "traefik.http.routers.whatsupdocker.entrypoints=web"
      - "traefik.http.services.whatsupdocker.loadbalancer.server.port=3000"
    networks:
      - traefik

# Jellyfin - All the media and cool stuff
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    logging:
      driver: json-file
    user: 1000:1000
    # network_mode: 'host' #- proxied through traefik
    volumes:
      - /containers/jellyfin/config:/config
      - /containers/jellyfin/cache:/cache
      - /data/media:/data/media
      - /data/media2:/data/media2:ro
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl}
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.hackerboy.xyz`)" # && PathPrefix(`/jellyfin`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

#Jellyseerr - Manages requests for the media library
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    # ports:
    # - 5055:5055
    volumes:
      - /containers/jellyseerr/config:/app/config
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.hackerboy.xyz`)" # && PathPrefix(`/jellyseerr`) "
      - "traefik.http.routers.jellyseerr.entrypoints=web"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"

# Uptime-kuma - Playing ping pong with all the cool containers
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /containers/uptime-kuma/data:/app/data
    # ports:
    #   - 3001:3001
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.hackerboy.xyz`)" # && PathPrefix(`/uptime-kuma`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=web"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"

# Bazarr - Manages and downloads subtitles based on my requirements
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /containers/bazarr/config:/config
      - /data/media:/data/media
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 6767:6767
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.hackerboy.xyz`)" # && PathPrefix(`/bazarr`)"
      - "traefik.http.routers.bazarr.entrypoints=web"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"

# Sonarr - Automatically download TV Shows via Usenet and the qBittorrent
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /containers/sonarr/config:/config
      - /data:/data
      - /etc/localtime:/etc/localtime:ro
        #- /path/to/downloadclient-downloads:/downloads #optional
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.hackerboy.xyz`)" # && PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

# Radarr - Automatically download movies via Usenet and the qBittorrent
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    # ports:
    #   - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /containers/radarr/config:/config
      - /data:/data
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.radarr.rule=Host(`radarr.hackerboy.xyz`)" # && PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

# Prowlarr - Gives the indexers to the arrs services
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /containers/prowlarr/config:/config
    # ports:
    #   - 9696:9696
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.hackerboy.xyz`)" # && PathPrefix(`/prowlarr`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

# Qbittorrent - We all know what it is
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - /containers/qbittorrent/config:/config
      - /data/torrents:/data/torrents
    # ports:
    #   - 9090:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.hackerboy.xyz`)" # && PathPrefix(`/qbittorrent`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"

networks:
  traefik:
    ipam:
      config:
        - subnet: 172.18.0.0/16

# Graveyard - Here lies the containers that I killed but may be revived someday (or not)

# # Watchtower - Keeping and eye on the containers' versions around3
#   watchtower:
#     container_name: watchtower
#     image: containrrr/watchtower
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       traefik:
#         ipv4_address: 172.18.0.#
#     labels:
#       - 'traefik.enable=true'
#       - "traefik.http.routers.watchtower.rule=Host(`watchtower.hackerboy.xyz`)" # && PathPrefix(`/jellyfin`)"
#       - "traefik.http.routers.watchtower.entrypoints=web"

# # Jackett
#   jackett:
#     image: lscr.io/linuxserver/jackett:latest
#     container_name: jackett
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${TZ}
#       - AUTO_UPDATE=true #optional
#       # - RUN_OPTS=true #optional
#     volumes:
#       - /containers/jackett/data:/config
#       - /data/torrents:/downloads
#     # ports:
#     #   # - 9117:9117
#     labels:
#       - 'traefik.enable=true'
#       - "traefik.http.routers.jackett.rule=Host(`jackett.hackerboy.xyz`)" # && PathPrefix(`/jackett`)"
#       - "traefik.http.routers.jackett.entrypoints=web"
#       - "traefik.http.services.jackett.loadbalancer.server.port=9117"
#     restart: unless-stopped
#     networks:
#       traefik:
#         ipv4_address: 172.18.0.#