services:
# Jellyfin - All the media and cool stuff
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    logging:
      driver: json-file
    # network_mode: 'host' # proxied through traefik
    volumes:
      - $CONTAINER_PATH/jellyfin/config:/config
      - $CONTAINER_PATH/jellyfin/cache:/cache
      - $DATA_PATH/media:/data/media
      - $DATA_PATH/media2:/data/media2:ro
      - /dev/shm:/data/transcode
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    user: $PUID:$PGID
    # profiles: ["media", "all"]
    environment:
      UMASK_SET: 022
      TZ: $TZ
    labels:
      - "traefik.enable=true"
      # Service (app port)
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      # Domain rule
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.$DOMAIN`)"
      # Entrypoint
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      # Enable tls
      - "traefik.http.routers.jellyfin.tls=true"
      # Redirect from http to https
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      
      # Homepage's
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=$ICON_WEB/jellyfin.png
      - homepage.href=https://jellyfin.$DOMAIN
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://jellyfin.$DOMAIN
      - homepage.widget.enableBlocks=true
      - homepage.widget.key=$JELLYFIN_KEY