version: '3.5'
services:
# Jellyfin - All the media and cool stuff
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    logging:
      driver: json-file
    # network_mode: 'host' # proxied through traefik
    volumes:
      - ${CONTAINER_PATH}/jellyfin/config:/config
      - ${CONTAINER_PATH}/jellyfin/cache:/cache
      - ${DATA_PATH}/media:/data/media
      - ${DATA_PATH}/media2:/data/media2:ro
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    environment:
      PUID: 1000
      GUID: 1000
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
                              #-------- Secure --------
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin-secure.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      # - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=${ICON_WEB}/jellyfin.png
      - homepage.href=https://jellyfin.${DOMAIN}
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://jellyfin.${DOMAIN}
      - homepage.widget.enableBlocks=true
      - homepage.widget.key=${JELLYFIN_KEY}

# Jellyseerr - Manages requests for the media library
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    # ports:
    # - 5055:5055
    volumes:
      - ${CONTAINER_PATH}/jellyseerr/config:/app/config
    restart: unless-stopped
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
                              #-------- Secure --------
      - "traefik.http.routers.jellyseerr-secure.rule=Host(`jellyseerr.${DOMAIN}`)"
      - "traefik.http.routers.jellyseerr-secure.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr-secure.tls=true"
      - "traefik.http.middlewares.jellyseerr-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Media
      - homepage.name=Jellyseerr
      - homepage.icon=${ICON_WEB}/jellyseerr.png
      - homepage.href=https://jellyseerr.${DOMAIN}
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=https://jellyseerr.${DOMAIN}
      - homepage.widget.key=${JELLYSEERR_KEY}

# Plex - All the media and cool stuff 2
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    # ports:
    #   - 32400:32400/tcp   # access to the Plex Media Server) [required]
    #   - 8324:8324/tcp     # controlling Plex for Roku via Plex Companion
    #   - 32469:32469/tcp   # access to the Plex DLNA Server
    #   - 1900:1900/udp     # access to the Plex DLNA Server
    #   - 32410:32410/udp   # current GDM network discovery
    #   - 32412:32412/udp   # current GDM network discovery
    #   - 32413:32413/udp   # current GDM network discovery
    #   - 32414:32414/udp   # current GDM network discovery
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=claim-X8S736d7su3J_Umz6rw-
      - ADVERTISE_IP=https://plex.hackerboy.xyz:443
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
    hostname: plexserver
    volumes:
      - ${CONTAINER_PATH}/plex/database:/config
      - ${CONTAINER_PATH}/plex/temp:/transcode
      - ${DATA_PATH}:/data
    labels:
    # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
                              #-------- Secure --------
      - "traefik.http.routers.plex-secure.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex-secure.entrypoints=websecure"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"
    
# Overseerr - Helps to find media you want to watch
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      # - PORT=5055 #optional
    # ports:
    #   - 5055:5055
    volumes:
      - ${DATA_PATH}/overseerr/config:/app/config
    restart: unless-stopped
    labels:
    # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
                              #-------- Secure --------
      - "traefik.http.routers.overseerr-secure.rule=Host(`overseerr.${DOMAIN}`)"
      - "traefik.http.routers.overseerr-secure.entrypoints=websecure"
      - "traefik.http.routers.overseerr-secure.tls=true"
      - "traefik.http.middlewares.overseerr-https-redirect.redirectscheme.scheme=https"
  
  # Tautulli - Monitor, view analytics, and receive notifications about Plex Media Server
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${CONTAINER_PATH}/tautulli/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # ports:
    #   - 8181:8181
    labels:
    # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
                              #-------- Secure --------
      - "traefik.http.routers.tautulli-secure.rule=Host(`tautulli.${DOMAIN}`)"
      - "traefik.http.routers.tautulli-secure.entrypoints=websecure"
      - "traefik.http.routers.tautulli-secure.tls=true"
      - "traefik.http.middlewares.tautulli-https-redirect.redirectscheme.scheme=https"

# Bazarr - Manages and downloads subtitles based on my requirements
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONTAINER_PATH}/bazarr/config:/config
      - ${DATA_PATH}/media:/data/media
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 6767:6767
    restart: unless-stopped
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
                              #-------- Secure --------
      - "traefik.http.routers.bazarr-secure.rule=Host(`bazarr.${DOMAIN}`)"
      - "traefik.http.routers.bazarr-secure.entrypoints=websecure"
      - "traefik.http.routers.bazarr-secure.tls=true"
      - "traefik.http.middlewares.bazarr-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Workers
      - homepage.name=Bazarr
      - homepage.icon=${ICON_WEB}/bazarr-light.png
      - homepage.href=https://bazarr.${DOMAIN}
      - homepage.widget.type=bazarr
      - homepage.widget.url=https://bazarr.${DOMAIN}
      - homepage.widget.key=${BAZARR_KEY}

# Sonarr - Automatically download TV Shows via Usenet and the qBittorrent
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TZ}
    volumes:
      - ${CONTAINER_PATH}/sonarr/config:/config
      - ${DATA_PATH}:/data
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
                              #-------- Secure --------
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr-secure.entrypoints=websecure"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Workers
      - homepage.name=Sonarr
      - homepage.icon=${ICON_WEB}/sonarr.png
      - homepage.href=https://sonarr.${DOMAIN}
      - homepage.widget.type=sonarr
      - homepage.widget.url=https://sonarr.${DOMAIN}
      - homepage.widget.key=${SONARR_KEY}
      - homepage.widget.enableQueue=true

# Radarr - Automatically download movies via Usenet and the qBittorrent
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    # ports:
    #   - 7878:7878
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_PATH}/radarr/config:/config
      - ${DATA_PATH}:/data
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
                              #-------- Secure --------
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr-secure.entrypoints=websecure"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Workers
      - homepage.name=Radarr
      - homepage.icon=${ICON_WEB}/radarr.png
      - homepage.href=https://radarr.${DOMAIN}
      - homepage.widget.type=radarr
      - homepage.widget.url=https://radarr.${DOMAIN}
      - homepage.widget.key=${RADARR_KEY}
      - homepage.widget.enableQueue=true

# Prowlarr - Gives the indexers to the arrs services
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TZ}
    volumes:
      - ${CONTAINER_PATH}/prowlarr/config:/config
    # ports:
    #   - 9696:9696
    restart: unless-stopped
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
                              #-------- Secure --------
      - "traefik.http.routers.prowlarr-secure.rule=Host(`prowlarr.${DOMAIN}`)"
      - "traefik.http.routers.prowlarr-secure.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-secure.tls=true"
      - "traefik.http.middlewares.prowlarr-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Workers
      - homepage.name=Prowlarr
      - homepage.icon=${ICON_WEB}/prowlarr.png
      - homepage.href=https://prowlarr.${DOMAIN}
      - homepage.widget.type=prowlarr
      - homepage.widget.url=https://prowlarr.${DOMAIN}
      - homepage.widget.key=${PROWLARR_KEY}

# Qbittorrent - We all know what it is
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    logging:
      driver: json-file
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${CONTAINER_PATH}/qbittorrent/config:/config
      - ${DATA_PATH}/torrents:/data/torrents
    # ports:
    #   - 9090:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped
    labels:
      # Traefik's
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
                              #-------- Secure --------
      - "traefik.http.routers.qbittorrent-secure.rule=Host(`qbittorrent.${DOMAIN}`)"
      - "traefik.http.routers.qbittorrent-secure.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent-secure.tls=true"
      - "traefik.http.middlewares.qbittorrent-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Downloads
      - homepage.name=qBittorrent
      - homepage.icon=${ICON_WEB}/qbittorrent.png
      - homepage.href=https://qbittorrent.${DOMAIN}
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=https://qbittorrent.${DOMAIN}
      - homepage.widget.username=${QBIT_USERNAME}
      - homepage.widget.password=${QBIT_PASSWORD}

networks:
  default:
    external: true
    name: traefik