services:
  # What's up Docker? - Just like watchtower but cooler
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    # ports:
    #   - 3000:3000
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      # Service (app port)
      - "traefik.http.services.wud.loadbalancer.server.port=3000"
      # Domain rule
      - "traefik.http.routers.wud.rule=Host(`wud.$DOMAIN`)"
      # Entrypoint
      - "traefik.http.routers.wud.entrypoints=websecure"
      # Enable tls
      - "traefik.http.routers.wud.tls=true"
      # Redirect from http to https
      - "traefik.http.middlewares.wud-https-redirect.redirectscheme.scheme=https"
      # Homepage's
      - homepage.group=Updates
      - homepage.name=What's up Docker
      - homepage.icon=$ICON_WEB/wud-light.png
      - homepage.href=https://whatsupdocker.$DOMAIN
      - homepage.widget.type=whatsupdocker
      - homepage.widget.url=https://whatsupdocker.$DOMAIN